-- SOMPO - Tabela de FAZENDA (cadastro pelo dashboard).
--
-- Uma fazenda pertence a um cliente (o dono/responsavel) e agrupa equipamentos. E cadastrada
-- pela tela "Fazendas" do painel: o navegador (logado) chama a API, que insere aqui usando a
-- SECRET key (service_role) - que ignora o RLS. A chave do ESP32 (anon) NAO acessa esta tabela.
--
-- Rode este script no SQL Editor do Supabase uma vez. E idempotente.
-- Depende da tabela `cliente` (FK); se ela nao existir, rode antes o preparar_supabase.sql +
-- dados_exemplo.sql (que criam/populam cliente).

create table if not exists public.fazenda (
  id_fazenda            bigint generated by default as identity primary key,
  nome                  text        not null,
  localizacao           text,
  area_ha               numeric,                 -- area em hectares (base p/ GPS/cerca virtual)
  fk_cliente_id_cliente bigint      references public.cliente(id_cliente),
  dispositivo_id        text,                    -- ESP32 que monitora esta fazenda (elo com a telemetria)
  criado_em             timestamptz not null default now()
);

-- Migracao p/ quem ja tinha a tabela: liga a fazenda a um dispositivo (perfil gestor_fazenda).
alter table public.fazenda add column if not exists dispositivo_id text;

create index if not exists idx_fazenda_cliente on public.fazenda (fk_cliente_id_cliente);

-- Seguranca: RLS ligada, sem policy para anon => a chave do ESP32 nao le nem escreve.
-- A API usa a SECRET key (service_role), que ignora o RLS e continua lendo/gravando.
alter table public.fazenda enable row level security;
