-- SOMPO fleet migration. Run after existing business/sensor/fazenda migrations.
-- Additive and repeatable. Does not execute preparar_supabase.sql or erase data.
-- API management uses service_role; browser/ESP32 roles use only token RPCs.
begin;

alter table public.equipamentos
 add column if not exists fk_fazenda_id_fazenda bigint references public.fazenda(id_fazenda),
 add column if not exists dispositivo_id text,
 add column if not exists ativo boolean not null default true,
 add column if not exists config_versao bigint not null default 1,
 add column if not exists config_versao_aplicada bigint,
 add column if not exists config_sincronizada_em timestamptz;
create unique index if not exists equipamentos_dispositivo_unique on public.equipamentos(dispositivo_id);
create index if not exists equipamentos_fazenda_idx on public.equipamentos(fk_fazenda_id_fazenda);

-- A customer with several farms does not identify an equipment's farm.
update public.equipamentos e set fk_fazenda_id_fazenda=f.id
from (select fk_cliente_id_cliente,min(id_fazenda) id from public.fazenda
      group by fk_cliente_id_cliente having count(*)=1) f
where e.fk_cliente_id_cliente=f.fk_cliente_id_cliente and e.fk_fazenda_id_fazenda is null;
-- The ONLY documented historical equipment/device mapping (dados_exemplo.sql).
update public.equipamentos e set dispositivo_id='SOMPO-ESP32'
where e.nome='Escavadeira Hidraulica 01' and e.dispositivo_id is null
 and (select count(*) from public.equipamentos where nome='Escavadeira Hidraulica 01')=1
 and not exists(select 1 from public.equipamentos where dispositivo_id='SOMPO-ESP32')
 and exists(select 1 from public.fazenda f where f.id_fazenda=e.fk_fazenda_id_fazenda
   and f.fk_cliente_id_cliente=e.fk_cliente_id_cliente and f.dispositivo_id='SOMPO-ESP32');

create table if not exists public.operadores (
 id_operador bigint generated by default as identity primary key,
 nome text not null check(length(btrim(nome))>0), matricula text,
 fk_fazenda_id_fazenda bigint not null references public.fazenda(id_fazenda),
 uid text not null unique check(uid ~ '^([0-9A-F]{8}|[0-9A-F]{14}|[0-9A-F]{20})$'),
 ativo boolean not null default true
);
create index if not exists operadores_fazenda_idx on public.operadores(fk_fazenda_id_fazenda);
create table if not exists public.operador_equipamento (
 equipamento_id bigint not null references public.equipamentos(id_equipamento),
 operador_id bigint not null references public.operadores(id_operador),
 ativo boolean not null default true, primary key(equipamento_id,operador_id)
);
create index if not exists operador_equipamento_operador_idx on public.operador_equipamento(operador_id);
create table if not exists public.credenciais_dispositivo (
 equipamento_id bigint primary key references public.equipamentos(id_equipamento),
 token_hash text not null check(token_hash ~ '^[0-9a-f]{64}$'),
 criado_em timestamptz not null default now()
);
create table if not exists public.registros_operacao (
 registro_id uuid primary key, dispositivo_id text not null,
 equipamento_id bigint not null references public.equipamentos(id_equipamento),
 operador_id bigint references public.operadores(id_operador), sessao_id uuid,
 tipo text not null check(tipo in ('inicio','fim','tentativa_negada')), motivo text, uid text,
 config_versao bigint not null check(config_versao>0), ocorrido_em timestamptz,
 recebido_em timestamptz not null default now(), boot_id uuid not null,
 sequencia bigint not null check(sequencia>=0), uptime_ms bigint not null check(uptime_ms>=0),
 check(tipo='tentativa_negada' or (sessao_id is not null and operador_id is not null))
);
-- A private receipt binds each protocol UUID to its original payload/category.
-- It also makes UUID uniqueness span all three protocol categories.
create table if not exists public.recibos_dispositivo (
 registro_id uuid primary key, equipamento_id bigint not null references public.equipamentos(id_equipamento),
 categoria text not null, payload jsonb not null
);

alter table public.telemetria
 add column if not exists registro_id uuid,
 add column if not exists equipamento_id bigint references public.equipamentos(id_equipamento),
 add column if not exists operador_id bigint references public.operadores(id_operador),
 add column if not exists sessao_id uuid, add column if not exists uid text,
 add column if not exists config_versao bigint, add column if not exists ocorrido_em timestamptz,
 add column if not exists recebido_em timestamptz not null default now(),
 add column if not exists boot_id uuid, add column if not exists sequencia bigint,
 add column if not exists uptime_ms bigint;
alter table public.eventos
 add column if not exists registro_id uuid,
 add column if not exists equipamento_id bigint references public.equipamentos(id_equipamento),
 add column if not exists operador_id bigint references public.operadores(id_operador),
 add column if not exists sessao_id uuid, add column if not exists uid text,
 add column if not exists config_versao bigint, add column if not exists ocorrido_em timestamptz,
 add column if not exists recebido_em timestamptz not null default now(),
 add column if not exists boot_id uuid, add column if not exists sequencia bigint,
 add column if not exists uptime_ms bigint;
create unique index if not exists telemetria_registro_unique on public.telemetria(registro_id);
create unique index if not exists eventos_registro_unique on public.eventos(registro_id);
create index if not exists telemetria_equipamento_data_idx on public.telemetria(equipamento_id,criado_em desc,id desc);
create index if not exists eventos_equipamento_data_idx on public.eventos(equipamento_id,criado_em desc,id desc);
create index if not exists registros_operacao_equipamento_idx on public.registros_operacao(equipamento_id,recebido_em desc);
create index if not exists registros_operacao_sessao_idx on public.registros_operacao(sessao_id,tipo);
create unique index if not exists registros_operacao_transicao_unique on public.registros_operacao(sessao_id,tipo) where tipo in ('inicio','fim');

create or replace function public.frota_validar_equipamento() returns trigger
language plpgsql set search_path=pg_catalog,public as $$
begin
 if TG_OP='UPDATE' then
  if OLD.fk_fazenda_id_fazenda is not null and NEW.fk_fazenda_id_fazenda is distinct from OLD.fk_fazenda_id_fazenda then
   raise exception 'A fazenda do equipamento nao pode ser transferida' using errcode='23514';
  end if;
  if OLD.dispositivo_id is not null and NEW.dispositivo_id is distinct from OLD.dispositivo_id then
   raise exception 'O dispositivo nao pode ser remanejado' using errcode='23514';
  end if;
  if NEW.ativo is distinct from OLD.ativo then NEW.config_versao:=OLD.config_versao+1; end if;
 end if;
 if NEW.dispositivo_id is not null and (btrim(NEW.dispositivo_id)='' or NEW.fk_fazenda_id_fazenda is null) then
  raise exception 'Dispositivo exige identificador e fazenda' using errcode='23514';
 end if;
 if NEW.fk_fazenda_id_fazenda is not null and not exists(
  select 1 from public.fazenda where id_fazenda=NEW.fk_fazenda_id_fazenda
   and fk_cliente_id_cliente is not distinct from NEW.fk_cliente_id_cliente) then
  raise exception 'Cliente do equipamento difere da fazenda' using errcode='23514';
 end if;
 return NEW;
end $$;
drop trigger if exists frota_validar_equipamento on public.equipamentos;
create trigger frota_validar_equipamento before insert or update on public.equipamentos
 for each row execute function public.frota_validar_equipamento();

create or replace function public.frota_validar_operador() returns trigger
language plpgsql set search_path=pg_catalog,public as $$
begin
 NEW.uid:=upper(regexp_replace(NEW.uid,'[-:[:space:]]','','g'));
 if TG_OP='UPDATE' and NEW.fk_fazenda_id_fazenda is distinct from OLD.fk_fazenda_id_fazenda then
  raise exception 'Operador nao pode ser transferido de fazenda' using errcode='23514';
 end if;
 return NEW;
end $$;
drop trigger if exists frota_validar_operador on public.operadores;
create trigger frota_validar_operador before insert or update on public.operadores
 for each row execute function public.frota_validar_operador();

create or replace function public.frota_versao_operador() returns trigger
language plpgsql set search_path=pg_catalog,public as $$
begin
 if NEW.uid is distinct from OLD.uid or NEW.ativo is distinct from OLD.ativo then
  update public.equipamentos set config_versao=config_versao+1
  where id_equipamento in(select equipamento_id from public.operador_equipamento where operador_id=NEW.id_operador);
 end if;
 return NEW;
end $$;
drop trigger if exists frota_versao_operador on public.operadores;
create trigger frota_versao_operador after update on public.operadores
 for each row execute function public.frota_versao_operador();

create or replace function public.frota_validar_vinculo() returns trigger
language plpgsql set search_path=pg_catalog,public as $$
begin
 if TG_OP='UPDATE' and (NEW.equipamento_id<>OLD.equipamento_id or NEW.operador_id<>OLD.operador_id) then
  raise exception 'Identidade do vinculo e imutavel' using errcode='23514';
 end if;
 if not exists(select 1 from public.equipamentos e join public.operadores o
  on o.fk_fazenda_id_fazenda=e.fk_fazenda_id_fazenda
  where e.id_equipamento=NEW.equipamento_id and o.id_operador=NEW.operador_id) then
  raise exception 'Operador e equipamento devem pertencer a mesma fazenda' using errcode='23514';
 end if;
 if TG_OP='INSERT' or NEW.ativo is distinct from OLD.ativo then
  update public.equipamentos set config_versao=config_versao+1 where id_equipamento=NEW.equipamento_id;
 end if;
 return NEW;
end $$;
drop trigger if exists frota_validar_vinculo on public.operador_equipamento;
create trigger frota_validar_vinculo before insert or update on public.operador_equipamento
 for each row execute function public.frota_validar_vinculo();

create or replace function public.frota_historico_imutavel() returns trigger
language plpgsql set search_path=pg_catalog,public as $$
begin raise exception 'Historico imutavel; revogue autorizacoes com ativo=false' using errcode='23514'; end $$;
drop trigger if exists frota_eventos_imutaveis on public.eventos;
create trigger frota_eventos_imutaveis before update or delete on public.eventos
 for each row execute function public.frota_historico_imutavel();
drop trigger if exists frota_operacoes_imutaveis on public.registros_operacao;
create trigger frota_operacoes_imutaveis before update or delete on public.registros_operacao
 for each row execute function public.frota_historico_imutavel();
drop trigger if exists frota_recibos_imutaveis on public.recibos_dispositivo;
create trigger frota_recibos_imutaveis before update or delete on public.recibos_dispositivo
 for each row execute function public.frota_historico_imutavel();
drop trigger if exists frota_vinculos_persistentes on public.operador_equipamento;
create trigger frota_vinculos_persistentes before delete on public.operador_equipamento
 for each row execute function public.frota_historico_imutavel();

create or replace function public.provisionar_dispositivo(p_equipamento_id bigint,p_token_hash text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 perform 1 from public.equipamentos where id_equipamento=p_equipamento_id
  and dispositivo_id is not null and fk_fazenda_id_fazenda is not null for update;
 if not found then raise exception 'Equipamento sem dispositivo/fazenda' using errcode='22023'; end if;
 -- Initial provisioning only: replacing a credential would strand offline data.
 insert into public.credenciais_dispositivo(equipamento_id,token_hash) values(p_equipamento_id,lower(p_token_hash));
 return jsonb_build_object('equipamento_id',p_equipamento_id);
end $$;

create or replace function public.definir_operadores_equipamento(p_equipamento_id bigint,p_operador_ids bigint[])
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_fazenda bigint; v_result jsonb;
begin
 select fk_fazenda_id_fazenda into v_fazenda from public.equipamentos where id_equipamento=p_equipamento_id for update;
 if v_fazenda is null or p_operador_ids is null then raise exception 'Equipamento/fazenda/lista invalido' using errcode='22023'; end if;
 if exists(select 1 from unnest(p_operador_ids) id where id is null or not exists(
  select 1 from public.operadores o where o.id_operador=id and o.fk_fazenda_id_fazenda=v_fazenda)) then
  raise exception 'Operador inexistente ou de outra fazenda' using errcode='23514';
 end if;
 update public.operador_equipamento set ativo=false where equipamento_id=p_equipamento_id
  and ativo and not (operador_id=any(p_operador_ids));
 insert into public.operador_equipamento(equipamento_id,operador_id,ativo)
  select p_equipamento_id,id,true from (select distinct unnest(p_operador_ids) id) ids
  on conflict(equipamento_id,operador_id) do update set ativo=true where not operador_equipamento.ativo;
 select coalesce(jsonb_agg(to_jsonb(v) order by operador_id),'[]'::jsonb) into v_result
  from public.operador_equipamento v where equipamento_id=p_equipamento_id;
 return v_result;
end $$;

create or replace function public.sincronizar_dispositivo(p_dispositivo_id text,p_token text)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_e public.equipamentos%rowtype; v_operadores jsonb;
begin
 select e.* into v_e from public.equipamentos e join public.credenciais_dispositivo c on c.equipamento_id=e.id_equipamento
 where e.dispositivo_id=p_dispositivo_id and c.token_hash=encode(sha256(convert_to(p_token,'UTF8')),'hex') for update of e;
 if not found then raise exception 'Credencial invalida' using errcode='28000'; end if;
 select coalesce(jsonb_agg(jsonb_build_object('operador_id',o.id_operador,'uid',o.uid) order by o.id_operador),'[]'::jsonb)
 into v_operadores from public.operadores o join public.operador_equipamento oe on oe.operador_id=o.id_operador
 where oe.equipamento_id=v_e.id_equipamento and oe.ativo and o.ativo and v_e.ativo;
 update public.equipamentos set config_versao_aplicada=v_e.config_versao,config_sincronizada_em=now()
 where id_equipamento=v_e.id_equipamento;
 return jsonb_build_object('equipamento_id',v_e.id_equipamento,'versao',v_e.config_versao,'operadores',v_operadores);
end $$;

create or replace function public.registrar_dispositivo(p_dispositivo_id text,p_token text,p_categoria text,p_registro jsonb)
returns jsonb language plpgsql security definer set search_path=pg_catalog,public as $$
declare
 v_e public.equipamentos%rowtype; v_recibo public.recibos_dispositivo%rowtype;
 v_t public.telemetria%rowtype; v_ev public.eventos%rowtype; v_op public.registros_operacao%rowtype;
 v_id uuid; v_operador bigint; v_sessao uuid; v_now timestamptz:=clock_timestamp(); v_data jsonb;
begin
 select e.* into v_e from public.equipamentos e join public.credenciais_dispositivo c on c.equipamento_id=e.id_equipamento
 where e.dispositivo_id=p_dispositivo_id and c.token_hash=encode(sha256(convert_to(p_token,'UTF8')),'hex');
 if not found then raise exception 'Credencial invalida' using errcode='28000'; end if;
 if p_categoria is null or p_categoria not in ('telemetria','eventos','operacao') or jsonb_typeof(p_registro) is distinct from 'object' then
  raise exception 'Categoria/registro invalido' using errcode='22023';
 end if;
 v_id:=(p_registro->>'registro_id')::uuid;
 v_operador:=(p_registro->>'operador_id')::bigint;
 v_sessao:=(p_registro->>'sessao_id')::uuid;
 if v_id is null or (p_registro->>'boot_id')::uuid is null or (p_registro->>'config_versao')::bigint is null
  or (p_registro->>'config_versao')::bigint<1 or (p_registro->>'sequencia')::bigint is null
  or (p_registro->>'sequencia')::bigint<0 or (p_registro->>'uptime_ms')::bigint is null
  or (p_registro->>'uptime_ms')::bigint<0 then
  raise exception 'Identidade/ordem do registro obrigatoria' using errcode='22023';
 end if;
 if (p_registro->>'equipamento_id') is not null and (p_registro->>'equipamento_id')::bigint<>v_e.id_equipamento
  or (p_registro->>'dispositivo_id') is not null and p_registro->>'dispositivo_id'<>p_dispositivo_id then
  raise exception 'Equipamento alheio a credencial' using errcode='42501';
 end if;
 if v_operador is not null and not exists(select 1 from public.operadores o
  join public.operador_equipamento oe on oe.operador_id=o.id_operador
  where o.id_operador=v_operador and o.fk_fazenda_id_fazenda=v_e.fk_fazenda_id_fazenda and oe.equipamento_id=v_e.id_equipamento) then
  raise exception 'Operador sem vinculo historico com o equipamento' using errcode='23514';
 end if;
 -- Serializes competing deliveries of a UUID, including different categories.
 perform pg_advisory_xact_lock(hashtextextended(v_id::text,0));
 select * into v_recibo from public.recibos_dispositivo where registro_id=v_id;
 if found then
  if v_recibo.equipamento_id<>v_e.id_equipamento or v_recibo.categoria<>p_categoria or v_recibo.payload<>p_registro then
   raise exception 'UUID reutilizado com payload conflitante' using errcode='23505';
  end if;
  return jsonb_build_object('ok',true,'duplicado',true);
 end if;
 if v_sessao is not null then
  perform pg_advisory_xact_lock(hashtextextended(v_sessao::text,1));
  if exists(select 1 from public.registros_operacao where sessao_id=v_sessao
   and (equipamento_id<>v_e.id_equipamento or operador_id is distinct from v_operador)) then
   raise exception 'Sessao de outro equipamento/operador' using errcode='23514';
  end if;
 end if;
 v_data:=p_registro||jsonb_build_object('equipamento_id',v_e.id_equipamento,'dispositivo_id',p_dispositivo_id,
  'recebido_em',v_now,'criado_em',coalesce((p_registro->>'ocorrido_em')::timestamptz,v_now));
 -- Explicit column lists: unknown JSON keys cannot become identifiers or SQL.
 if p_categoria='telemetria' then
  v_t:=jsonb_populate_record(null::public.telemetria,v_data);
  insert into public.telemetria(dispositivo_id,criado_em,temp_escape,temp_ambiente,umidade_ar,chama_detectada,
   vibracao,motor_ligado,capo_aberto,tanque_aberto,operador_autorizado,nivel_risco,registro_id,equipamento_id,
   operador_id,sessao_id,uid,config_versao,ocorrido_em,recebido_em,boot_id,sequencia,uptime_ms)
  values(v_t.dispositivo_id,v_t.criado_em,v_t.temp_escape,v_t.temp_ambiente,v_t.umidade_ar,v_t.chama_detectada,
   v_t.vibracao,v_t.motor_ligado,v_t.capo_aberto,v_t.tanque_aberto,v_t.operador_autorizado,v_t.nivel_risco,
   v_t.registro_id,v_t.equipamento_id,v_t.operador_id,v_t.sessao_id,v_t.uid,v_t.config_versao,
   v_t.ocorrido_em,v_t.recebido_em,v_t.boot_id,v_t.sequencia,v_t.uptime_ms);
 elsif p_categoria='eventos' then
  v_ev:=jsonb_populate_record(null::public.eventos,v_data);
  insert into public.eventos(dispositivo_id,criado_em,tipo,severidade,temp_escape,detalhes,registro_id,equipamento_id,
   operador_id,sessao_id,uid,config_versao,ocorrido_em,recebido_em,boot_id,sequencia,uptime_ms)
  values(v_ev.dispositivo_id,v_ev.criado_em,v_ev.tipo,v_ev.severidade,v_ev.temp_escape,v_ev.detalhes,
   v_ev.registro_id,v_ev.equipamento_id,v_ev.operador_id,v_ev.sessao_id,v_ev.uid,v_ev.config_versao,
   v_ev.ocorrido_em,v_ev.recebido_em,v_ev.boot_id,v_ev.sequencia,v_ev.uptime_ms);
 else
  v_op:=jsonb_populate_record(null::public.registros_operacao,v_data);
  insert into public.registros_operacao values(v_op.*);
 end if;
 insert into public.recibos_dispositivo values(v_id,v_e.id_equipamento,p_categoria,p_registro);
 return jsonb_build_object('ok',true,'duplicado',false);
end $$;

create or replace view public.sessoes_operacao with(security_invoker=true) as
 select coalesce(i.sessao_id,f.sessao_id) sessao_id,
 coalesce(i.equipamento_id,f.equipamento_id) equipamento_id,
 coalesce(i.operador_id,f.operador_id) operador_id,e.fk_fazenda_id_fazenda fazenda_id,
 e.nome equipamento_nome,o.nome operador_nome,i.ocorrido_em inicio_em,f.ocorrido_em fim_em,
 greatest(i.recebido_em,f.recebido_em) recebido_em,
 case when f.registro_id is null then 'aberta'
      when f.motivo in ('reinicio','reinicializacao','interrompida','reboot') then 'interrompida'
      else 'encerrada' end status,f.motivo
 from (select * from public.registros_operacao where tipo='inicio') i
 full join (select * from public.registros_operacao where tipo='fim') f on f.sessao_id=i.sessao_id
 join public.equipamentos e on e.id_equipamento=coalesce(i.equipamento_id,f.equipamento_id)
 left join public.operadores o on o.id_operador=coalesce(i.operador_id,f.operador_id);
create or replace view public.ultima_telemetria with(security_invoker=true) as
 select distinct on(dispositivo_id) * from public.telemetria order by dispositivo_id,criado_em desc,id desc;

create or replace function public.concluir_migracao_dispositivos() returns jsonb
language plpgsql security definer set search_path=pg_catalog,public as $$
begin
 lock table public.equipamentos in share row exclusive mode;
 if exists(select 1 from public.equipamentos e left join public.credenciais_dispositivo c on c.equipamento_id=e.id_equipamento
  where e.dispositivo_id is not null and (c.equipamento_id is null or e.config_sincronizada_em is null
   or e.config_versao_aplicada is distinct from e.config_versao)) then
  raise exception 'Todos dispositivos precisam credencial e configuracao sincronizada' using errcode='23514';
 end if;
 drop policy if exists "anon insere telemetria" on public.telemetria;
 drop policy if exists "anon insere eventos" on public.eventos;
 revoke insert on public.telemetria,public.eventos from anon,authenticated;
 return jsonb_build_object('ok',true);
end $$;

alter table public.equipamentos enable row level security;
alter table public.operadores enable row level security;
alter table public.operador_equipamento enable row level security;
alter table public.credenciais_dispositivo enable row level security;
alter table public.registros_operacao enable row level security;
alter table public.recibos_dispositivo enable row level security;
revoke all on public.operadores,public.operador_equipamento,public.credenciais_dispositivo,
 public.registros_operacao,public.recibos_dispositivo,public.sessoes_operacao,public.ultima_telemetria from public,anon,authenticated;
revoke update,delete,truncate on public.eventos,public.registros_operacao,public.recibos_dispositivo from anon,authenticated,service_role;
grant select,insert,update on public.equipamentos,public.operadores,public.operador_equipamento to service_role;
grant select on public.credenciais_dispositivo,public.registros_operacao,public.sessoes_operacao,public.ultima_telemetria to service_role;
grant usage,select on sequence public.operadores_id_operador_seq to service_role;

-- New PostgreSQL functions default to PUBLIC EXECUTE; explicitly close every one.
revoke all on function public.frota_validar_equipamento(),public.frota_validar_operador(),
 public.frota_versao_operador(),public.frota_validar_vinculo(),public.frota_historico_imutavel(),
 public.provisionar_dispositivo(bigint,text),public.definir_operadores_equipamento(bigint,bigint[]),
 public.sincronizar_dispositivo(text,text),public.registrar_dispositivo(text,text,text,jsonb),
 public.concluir_migracao_dispositivos() from public,anon,authenticated;
grant execute on function public.sincronizar_dispositivo(text,text),public.registrar_dispositivo(text,text,text,jsonb)
 to anon,authenticated,service_role;
grant execute on function public.provisionar_dispositivo(bigint,text),public.definir_operadores_equipamento(bigint,bigint[]),
 public.concluir_migracao_dispositivos() to service_role;
commit;
