-- SOMPO: mapa da carteira (coordenadas da fazenda) e ocorrencias (tratamento dos alertas).
-- Aditivo e repetivel: so acrescenta colunas e regras; nao apaga nem altera dados.
-- Rodar depois de frota.sql e exclusoes.sql, no SQL Editor do Supabase.
begin;

-- Coordenadas opcionais (graus decimais). Fazenda sem coordenada fica fora do mapa.
alter table public.fazenda
 add column if not exists latitude numeric(9,6),
 add column if not exists longitude numeric(9,6);
alter table public.fazenda drop constraint if exists fazenda_latitude_valida;
alter table public.fazenda add constraint fazenda_latitude_valida check (latitude between -90 and 90);
alter table public.fazenda drop constraint if exists fazenda_longitude_valida;
alter table public.fazenda add constraint fazenda_longitude_valida check (longitude between -180 and 180);
alter table public.fazenda drop constraint if exists fazenda_coordenadas_juntas;
alter table public.fazenda add constraint fazenda_coordenadas_juntas check ((latitude is null) = (longitude is null));

-- Ocorrencia: um alerta (ou um relato manual) que alguem precisa verificar ate resolver.
create table if not exists public.ocorrencias (
 id_ocorrencia bigint generated by default as identity primary key,
 fazenda_id bigint not null references public.fazenda(id_fazenda),
 equipamento_id bigint references public.equipamentos(id_equipamento),
 evento_id bigint references public.eventos(id),
 tipo text,
 titulo text not null check (length(btrim(titulo)) > 0),
 descricao text,
 status text not null default 'aberta' check (status in ('aberta','em_verificacao','resolvida')),
 responsavel_id bigint references public.usuario(id_usuario),
 nota text,
 criado_por text,
 criado_em timestamptz not null default now(),
 atualizado_em timestamptz not null default now(),
 resolvido_em timestamptz
);
-- Um alerta vira no maximo uma ocorrencia; relatos manuais (sem evento) nao tem limite.
create unique index if not exists ocorrencias_evento_unique on public.ocorrencias(evento_id) where evento_id is not null;
create index if not exists ocorrencias_fazenda_status_idx on public.ocorrencias(fazenda_id, status);

-- Datas mantidas pelo banco: atualizado_em a cada mudanca; resolvido_em ao resolver (e limpo ao reabrir).
create or replace function public.ocorrencias_datas() returns trigger language plpgsql as $$
begin
 new.atualizado_em := now();
 if new.status = 'resolvida' then
  new.resolvido_em := coalesce(case when tg_op = 'UPDATE' and old.status = 'resolvida' then old.resolvido_em end, now());
 else
  new.resolvido_em := null;
 end if;
 return new;
end $$;
drop trigger if exists ocorrencias_datas on public.ocorrencias;
create trigger ocorrencias_datas before insert or update on public.ocorrencias
 for each row execute function public.ocorrencias_datas();

alter table public.ocorrencias enable row level security;
revoke all on public.ocorrencias from anon, authenticated;
grant select, insert, update on public.ocorrencias to service_role;
grant usage, select on sequence public.ocorrencias_id_ocorrencia_seq to service_role;
revoke all on function public.ocorrencias_datas() from public, anon, authenticated;

commit;
