-- SOMPO - Preparacao do Supabase para o projeto do sensor.
--
-- Rode ESTE script no SQL Editor do Supabase ANTES de tudo (assim que tiver acesso).
-- Ele cria as tabelas que o ESP32 grava e a API le, a view de resumo, os indices e
-- a seguranca (RLS). E idempotente: pode rodar de novo sem quebrar.
--
-- O schema abaixo bate EXATAMENTE com o que o firmware envia (enviarTelemetria /
-- dispararEvento em src/app.ino) e com o que a API consulta (api/supabase_client.py).
--
-- Obs.: este arquivo substitui, para um projeto novo/limpo, o politicas_rls.sql
-- (que assume tambem tabelas de negocio - cliente/sinistros/etc - que voce pode
-- nao ter). Aqui so mexemos nas tres coisas do sensor.

-- ==========================================================================
-- 1. Tabelas
-- ==========================================================================

-- Telemetria: amostra periodica enviada pelo ESP32 (a cada ~10s).
create table if not exists public.telemetria (
  id              bigint generated by default as identity primary key,
  dispositivo_id  text        not null,
  criado_em       timestamptz not null default now(),
  temp_escape     real,
  umidade_ar      real,
  chama_detectada boolean,
  vibracao        real,
  motor_ligado    boolean,
  distancia_cm    real,
  em_movimento    boolean,
  nivel_risco     text
);

-- Eventos: gravados so quando dispara (furto/incendio). 'detalhes' e JSON livre.
create table if not exists public.eventos (
  id              bigint generated by default as identity primary key,
  dispositivo_id  text        not null,
  criado_em       timestamptz not null default now(),
  tipo            text        not null,
  severidade      smallint,
  temp_escape     real,
  detalhes        jsonb
);

-- ==========================================================================
-- 2. View de resumo diario (a API le em /resumo e /relatorio/bruto; ninguem escreve)
-- ==========================================================================
-- security_invoker = true: quem consulta a view usa as proprias permissoes. A API
-- usa a secret key (service_role), que le tudo; um anon veria nada (seguro).
create or replace view public.resumo_diario
  with (security_invoker = true) as
select
  dispositivo_id,
  (criado_em at time zone 'America/Sao_Paulo')::date as dia,
  count(*)                              as amostras,
  round(avg(temp_escape)::numeric, 1)   as temp_escape_media,
  max(temp_escape)                      as temp_escape_max,
  round(avg(vibracao)::numeric, 2)      as vibracao_media,
  bool_or(chama_detectada)              as houve_chama,
  bool_or(em_movimento)                 as houve_movimento
from public.telemetria
group by dispositivo_id, (criado_em at time zone 'America/Sao_Paulo')::date;

-- ==========================================================================
-- 3. Indices (as consultas filtram por dispositivo_id e ordenam por data desc)
-- ==========================================================================
create index if not exists idx_telemetria_disp_data
  on public.telemetria (dispositivo_id, criado_em desc);
create index if not exists idx_eventos_disp_data
  on public.eventos (dispositivo_id, criado_em desc);

-- ==========================================================================
-- 4. Seguranca (RLS): a chave do ESP32 (publishable/anon) SO INSERE
-- ==========================================================================
-- Sem isso, a chave gravada na flash do ESP32 seria chave de administrador.
alter table public.telemetria enable row level security;
alter table public.eventos    enable row level security;

drop policy if exists "anon insere telemetria" on public.telemetria;
create policy "anon insere telemetria" on public.telemetria
  for insert to anon with check (true);

drop policy if exists "anon insere eventos" on public.eventos;
create policy "anon insere eventos" on public.eventos
  for insert to anon with check (true);

-- Nenhuma policy de select/update/delete para 'anon' => negado por padrao.
-- A API usa a SECRET key (service_role), que ignora o RLS e continua lendo tudo.
-- A trilha de evidencia (eventos) nao pode ser reescrita nem apagada:
revoke update, delete on public.eventos from anon, authenticated;

-- ==========================================================================
-- 5. Conferencia (opcional) - deve mostrar rowsecurity = true nas duas tabelas
-- ==========================================================================
-- select tablename, rowsecurity from pg_tables
--   where schemaname = 'public' and tablename in ('telemetria','eventos');
-- select tablename, policyname, cmd, roles from pg_policies
--   where schemaname = 'public' and tablename in ('telemetria','eventos');
