-- SOMPO - Perfis de acesso (role-based) do painel.
--
-- Cria a tabela `usuario` (login com role + fazenda vinculada) e semeia 3 logins de teste:
--   sompo            -> role 'sompo'          (subscritor: ve tudo, cadastra fazendas/clientes)
--   gestor.santarita -> role 'gestor_fazenda' (ve so a Fazenda Santa Rita)
--   gestor.valeverde -> role 'gestor_fazenda' (ve so a Fazenda Vale Verde)
--
-- Senhas: a coluna guarda HASH (werkzeug). Os seeds entram BLOQUEADOS ('!', nunca confere);
-- defina a senha de cada um com:  python tools/definir_senha.py <usuario>
-- (senha em texto puro de bancos antigos vira hash no primeiro login ou com
-- tools/migrar_senhas_hash.py). O RLS impede a chave anon (ESP32) de ler esta tabela;
-- so a API (secret key/service_role) le.
--
-- Ordem: rode ANTES o preparar_supabase.sql, o dados_exemplo.sql e o fazenda.sql (com a coluna
-- dispositivo_id). Este script e idempotente.

-- ==========================================================================
-- 1. Fazendas demo (idempotentes) com o dispositivo que cada uma monitora
-- ==========================================================================
insert into public.fazenda (nome, localizacao, area_ha, fk_cliente_id_cliente, dispositivo_id)
select 'Fazenda Santa Rita', 'Ribeirao Preto/SP', 1200,
       (select id_cliente from public.cliente where cnpj = '12.345.678/0001-90'),
       'SOMPO-ESP32'
where not exists (select 1 from public.fazenda where nome = 'Fazenda Santa Rita');

insert into public.fazenda (nome, localizacao, area_ha, fk_cliente_id_cliente, dispositivo_id)
select 'Fazenda Vale Verde', 'Jundiai/SP', 800,
       (select id_cliente from public.cliente where cnpj = '98.765.432/0001-10'),
       'SOMPO-ESP32-SIM'
where not exists (select 1 from public.fazenda where nome = 'Fazenda Vale Verde');

-- Garante o dispositivo mesmo se a fazenda ja existia sem ele.
update public.fazenda set dispositivo_id = 'SOMPO-ESP32'     where nome = 'Fazenda Santa Rita' and dispositivo_id is null;
update public.fazenda set dispositivo_id = 'SOMPO-ESP32-SIM' where nome = 'Fazenda Vale Verde' and dispositivo_id is null;

-- ==========================================================================
-- 2. Tabela de usuarios (perfis)
-- ==========================================================================
create table if not exists public.usuario (
  id_usuario            bigint generated by default as identity primary key,
  usuario               text        not null unique,
  senha                 text        not null,   -- TEXTO PLANO (demo academica)
  role                  text        not null,   -- 'sompo' | 'gestor_fazenda'
  fk_fazenda_id_fazenda bigint      references public.fazenda(id_fazenda),
  criado_em             timestamptz not null default now()
);

alter table public.usuario enable row level security;  -- sem policy anon => ESP32 nao le senhas

-- ==========================================================================
-- 3. Seeds dos 3 logins de teste
-- ==========================================================================
insert into public.usuario (usuario, senha, role, fk_fazenda_id_fazenda)
select 'sompo', '!', 'sompo', null
where not exists (select 1 from public.usuario where usuario = 'sompo');

-- Renomeia os logins antigos (fazenda1/fazenda2), se ja existirem, para os nomes didaticos.
update public.usuario set usuario = 'gestor.santarita', senha = '!' where usuario = 'fazenda1';
update public.usuario set usuario = 'gestor.valeverde', senha = '!' where usuario = 'fazenda2';

insert into public.usuario (usuario, senha, role, fk_fazenda_id_fazenda)
select 'gestor.santarita', '!', 'gestor_fazenda',
       (select id_fazenda from public.fazenda where nome = 'Fazenda Santa Rita')
where not exists (select 1 from public.usuario where usuario = 'gestor.santarita');

insert into public.usuario (usuario, senha, role, fk_fazenda_id_fazenda)
select 'gestor.valeverde', '!', 'gestor_fazenda',
       (select id_fazenda from public.fazenda where nome = 'Fazenda Vale Verde')
where not exists (select 1 from public.usuario where usuario = 'gestor.valeverde');

-- ==========================================================================
-- 4. Telemetria/eventos simulados para o 2o dispositivo (para o gestor2 ver dado distinto)
-- ==========================================================================
insert into public.telemetria (dispositivo_id, temp_escape, temp_ambiente, umidade_ar, vibracao, motor_ligado, nivel_risco)
select 'SOMPO-ESP32-SIM', 61.0, 29.5, 55.0, 0.03, false, 'SEGURO'
where not exists (select 1 from public.telemetria where dispositivo_id = 'SOMPO-ESP32-SIM');

insert into public.telemetria (dispositivo_id, temp_escape, temp_ambiente, umidade_ar, vibracao, motor_ligado, nivel_risco)
select 'SOMPO-ESP32-SIM', 480.0, 31.0, 52.0, 0.05, true, 'ATENCAO'
where (select count(*) from public.telemetria where dispositivo_id = 'SOMPO-ESP32-SIM') < 2;

insert into public.eventos (dispositivo_id, tipo, severidade, temp_escape, detalhes)
select 'SOMPO-ESP32-SIM', 'escape_atencao', 2, 480.0, '{"limiar_c":450}'::jsonb
where not exists (select 1 from public.eventos where dispositivo_id = 'SOMPO-ESP32-SIM');

-- ==========================================================================
-- 5. Conferencia (opcional)
-- ==========================================================================
-- select u.usuario, u.role, f.nome as fazenda, f.dispositivo_id
--   from public.usuario u left join public.fazenda f on f.id_fazenda = u.fk_fazenda_id_fazenda
--   order by u.usuario;
