-- ONLY in a disposable PostgreSQL database. Never run against Supabase.
create role anon;
create role authenticated;
create role service_role bypassrls;
create table public.cliente (id_cliente bigint primary key, nome text);
create table public.equipamentos (
 id_equipamento bigint generated by default as identity primary key, nome text not null,
 tipo text, modelo text, fabricacao date, ultima_manutencao date, valor_segurado numeric,
 fk_cliente_id_cliente bigint references public.cliente
);
create table public.fazenda (
 id_fazenda bigint primary key, nome text, fk_cliente_id_cliente bigint references public.cliente,
 dispositivo_id text
);
create table public.telemetria (
 id bigint generated by default as identity primary key, dispositivo_id text not null,
 criado_em timestamptz not null default now(), temp_escape real, temp_ambiente real,
 umidade_ar real, chama_detectada boolean, vibracao real, motor_ligado boolean,
 capo_aberto boolean, tanque_aberto boolean, operador_autorizado boolean, nivel_risco text
);
create table public.usuario (
 id_usuario bigint generated by default as identity primary key,
 usuario text not null unique, senha text not null, role text not null,
 fk_fazenda_id_fazenda bigint references public.fazenda,
 criado_em timestamptz not null default now()
);
create table public.eventos (
 id bigint generated by default as identity primary key, dispositivo_id text not null,
 criado_em timestamptz not null default now(), tipo text not null, severidade smallint,
 temp_escape real, detalhes jsonb
);
alter table telemetria enable row level security;
alter table eventos enable row level security;
grant usage on schema public to anon,authenticated,service_role;
grant all on all tables in schema public to service_role;
grant insert on telemetria,eventos to anon;
grant usage on all sequences in schema public to anon,service_role;
create policy "anon insere telemetria" on telemetria for insert to anon with check(true);
create policy "anon insere eventos" on eventos for insert to anon with check(true);
insert into cliente values (1,'Um'),(2,'Dois'),(3,'Ambiguo');
insert into fazenda values (1,'Um',1,'SOMPO-ESP32'),(2,'Dois',2,'DEVICE-2'),(3,'Tres',3,null),(4,'Quatro',3,null);
insert into equipamentos(nome,fk_cliente_id_cliente) values
 ('Escavadeira Hidraulica 01',1),('Retroescavadeira 02',1),('Caminhao',2),('Ambiguo',3);
insert into telemetria(dispositivo_id,temp_escape) values ('SOMPO-ESP32',123);
insert into eventos(dispositivo_id,tipo) values ('SOMPO-ESP32','incendio');
